name: esm-tutorials
channels:
    - conda-forge
    - defaults
dependencies:

    - python
    - pip

    # notebooks
    - jupyter
    - jupyterlab
    - nb_conda

    # utilities
    - ipython
    - numpy
    - scipy
    - pandas
    - cartopy
    - geopandas
    - networkx
    - matplotlib
    - yaml

    # optimisation
    - pyomo
    - scikit-learn
    - glpk
    - ipopt

    # power system analysis
    - pypsa
